import Link from 'next/link'
import styles from './styles/home.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container'>
        <div className='row'>
          <Link href="/" className={styles.title}><h1 className={styles.title}>Gallery</h1></Link>
        {children}

        </div>
        
        </body>
    </html>
  )
}
